
name: Build Nodejs and publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Nodejs version to build'
        required: true
        default: 'v20.11.1'
 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: download nodejs sources
        run: wget https://github.com/nodejs/node/archive/refs/tags/$NODE_VERSION.zip && unzip $NODE_VERSION.zip
        env:
          NODE_VERSION: ${{ inputs.version }}

      - name: Build nodejs
        run: |
          apt-get update && apt-get install ninja-build python-is-python3 -y
          ./configure --ninja
          ninja -C out/Release    
        working-directory: ${{ inputs.version }}
